### ISSUE TITLE
The employees need to be able to register a client so they can manage the client fidelity program.

### ISSUE THREAD

**Issue by aimproxy** [aimproxy-estg-ipp/PAW_AC_8200383_8200322_8200387#2]
- [ ] Rotas
- [x] Modelos
- [ ] Views

**Comment by aimproxy** [comment]
- [x] Ver link mais tarde: https://stackoverflow.com/questions/18022365/mongoose-validate-email-syntax
- [ ] Acrescentar estes parametros a todas as chaves da coleção
```js
var EmailSchema = new Schema({
    email: {
        type: String,
        trim: true,
        lowercase: true,
        unique: true,
        required: 'Email address is required',
        validate: [validateEmail, 'Please fill a valid email address'],
    }
});
```

**Comment by simaosantos01** [comment]
- When creating a new Employee, the accumulated_balance must be equal to 0

**Comment by aimproxy** [comment]
- [ ] Add Password Validator and Hash function
