### ISSUE TITLE
The employees need to be able to register a purchase on-site, whether the client has an account or not, so they can retain customer purchase history.

### ISSUE THREAD

**Issue by aimproxy** [aimproxy-estg-ipp/PAW_AC_8200383_8200322_8200387#3]

**Comment by simaosantos01** [comment]
**Handling Purchases**

- Case 1:  _Client has account_

Find client by his ID and relate the purchase to him.

- Case 2:  _Client does not have account_

Is it mandatory to have an account to make a purchase?
If so, it should be possible to create an account during the purchase process.
If not, what info should be stored about the costumer? #2

**Comment by aimproxy** [comment]
Gostei do metodo de validação mas pensa em por uma função para isso do genero `isOnlinePurchase()`

https://github.com/aimproxy-estg-ipp/PAW_AC_8200383_8200322_8200387/blob/purchases_%233/src/purchases/models/PurchaseModel.js#L53

**Comment by aimproxy** [comment]
Eu estivea rever o teu commit tu colocastes a logica do lado do DAO, eu relembro que os DAO's são um layer de inderação para executar queries na base de dados estes não devem conter logica a nao ser de validação dos schema. Por exemplo a logica que tu escrevestes na função `addInStorePurchase` deve pertencer ao controller

**Comment by aimproxy** [comment]
```js
try {
        costumer = await findCostumer(schema.reader_card_num)
        if (costumer == null) {
            throw new APIError(
                new Error('param: reader_card_num does not exists. '),
                500,
            )
        }

        await spentBalanceExists(schema.reader_card_num, schema.spent_balance)
        schema.subtotal = await calculateSubtotal(schema.isbn)
        schema.vat = await getVat()
        schema.total = schema.vat * schema.subtotal + schema.subtotal //apply discount and update balance
        schema.employee_num = '1' //brute force

        const purchase = new PurchaseModel(schema)
        await purchase.validate()
        await purchase.save()
    } catch (e) {
        throw new APIError(e, 500)
    }
```

Tu não podes dar throw dentro do try catch

**Comment by SweetDreamZzzz** [comment]
```js
const addCustomer = async (schema) => {
    let validatedSchema = null

    try {
        validatedSchema = await createCustomerSchema.validateAsync(schema)
    } catch (e) {
        throw new APIError(e)
    }

    const found = await findCustomerByEmail(validatedSchema.email)
    if (found) {
        throw APIError.CustomMessage('Customer already exists')
    }

    try {
        const customer = new CustomerModel(validatedSchema)
        await customer.validate()
        await customer.save()
    } catch (e) {
        throw new APIError(e, 500)
    }
}
```
Neste caso estás a dar throw também.

**Comment by simaosantos01** [comment]
Já corrijo isso. Erro meu :(

**Comment by simaosantos01** [comment]
Define function to validate model: https://stackoverflow.com/questions/22405975/how-to-validate-string-length-with-mongoose
